apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossplane
  template:
    metadata:
      labels:
        app: crossplane
    spec:
      containers:
        - name: crossplane
          image: crossplane/crossplane:v1.16.0
          ports:
            - containerPort: 9443
